# Generated by Django 5.1 on 2025-02-24 11:31

import django.db.models.deletion
import django.utils.timezone
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_payment_amount_paid_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount_percentage", models.FloatField()),
                ("active", models.BooleanField(default=True)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "end_date",
                    models.DateField(default=products.models.get_default_end_date),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
